#!/bin/sh
set -a
# Enable this setting instead of BLOG_HOST if running behind a reverse
# proxy.
# BLOG_PROXY=localhost:8000

# Hostname and port on which to listen.  Disable if running behind a
# proxy.  See BLOG_PROXY for that case.
BLOG_HOST=localhost:8000

# The username for the admin user
BLOG_ADMIN_USER=admin
# The password for the admin user
BLOG_ADMIN_PASS=admin

# Enable these if you want to use TLS.

# Path to the TLS private key file
# BLOG_TLS_KEY=tls.key

# Path to the TLS certificate file
# BLOG_TLS_CERT=tls.crt

exec "$@"